from sqlalchemy import Column, String, Float, Integer, DateTime, Boolean, Text, Date, ForeignKey, Index
from sqlalchemy.orm import relationship
from sqlalchemy.sql import func
from datetime import datetime
from database import Base

class User(Base):
    """Store user information from Clerk or registrations"""
    __tablename__ = "users"
    
    id = Column(String, primary_key=True, index=True)  # Clerk user ID or custom ID
    email = Column(String, unique=True, index=True, nullable=False)
    full_name = Column(String, nullable=True)
    first_name = Column(String, nullable=True)
    last_name = Column(String, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow, index=True)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    telemetry_records = relationship("ScrollTelemetryRecord", back_populates="user", cascade="all, delete-orphan")
    interventions = relationship("Intervention", back_populates="user", cascade="all, delete-orphan")
    profiles = relationship("UserProfile", back_populates="user", cascade="all, delete-orphan")
    
    __table_args__ = (
        Index('idx_user_created_at', 'created_at'),
    )

class ScrollTelemetryRecord(Base):
    """Store scroll telemetry data for analytics and graphing"""
    __tablename__ = "telemetry_records"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String, ForeignKey("users.id"), nullable=False, index=True)
    platform = Column(String, nullable=False)  # e.g., Twitter, TikTok, Reddit
    scroll_velocity = Column(Float, nullable=False)  # pixels per second
    posts_bypassed = Column(Integer, nullable=False)
    dwell_time_avg = Column(Float, nullable=False)  # average dwell time in seconds
    clicks = Column(Integer, nullable=False)
    mindless_score = Column(Float, default=0.0, index=True)  # Calculated mindless score
    intervention_triggered = Column(Boolean, default=False, index=True)
    intervention_message = Column(Text, nullable=True)
    recorded_at = Column(DateTime, default=datetime.utcnow, index=True)
    date = Column(Date, default=func.current_date(), index=True)  # For daily aggregations
    
    # Relationships
    user = relationship("User", back_populates="telemetry_records")
    
    __table_args__ = (
        Index('idx_telemetry_user_date', 'user_id', 'date'),
        Index('idx_telemetry_platform', 'platform'),
    )

class Intervention(Base):
    """Track interventions triggered for users"""
    __tablename__ = "interventions"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String, ForeignKey("users.id"), nullable=False, index=True)
    triggered_at = Column(DateTime, default=datetime.utcnow, index=True)
    date = Column(Date, default=func.current_date(), index=True)  # For daily counts
    mindless_score = Column(Float, nullable=False)
    message = Column(Text, nullable=False)
    user_acknowledged = Column(Boolean, default=False)
    
    # Relationships
    user = relationship("User", back_populates="interventions")
    
    __table_args__ = (
        Index('idx_intervention_user_date', 'user_id', 'date'),
    )

class UserProfile(Base):
    """Store generated psychological profiles for users"""
    __tablename__ = "user_profiles"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String, ForeignKey("users.id"), nullable=False, unique=True, index=True)
    profile_text = Column(Text, nullable=False)  # Generated by ASI-1
    generated_at = Column(DateTime, default=datetime.utcnow, index=True)
    date = Column(Date, default=func.current_date())  # Date profile was generated
    telemetry_count = Column(Integer, default=0)  # How many telemetry records this was based on
    
    # Relationships
    user = relationship("User", back_populates="profiles")

class DailyStats(Base):
    """Aggregated daily statistics for dashboard graphing"""
    __tablename__ = "daily_stats"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String, ForeignKey("users.id"), nullable=False, index=True)
    date = Column(Date, nullable=False, index=True)
    
    # Metrics for graphing
    total_sessions = Column(Integer, default=0)
    total_scroll_velocity = Column(Float, default=0.0)
    avg_scroll_velocity = Column(Float, default=0.0)
    total_posts_bypassed = Column(Integer, default=0)
    avg_dwell_time = Column(Float, default=0.0)
    total_clicks = Column(Integer, default=0)
    intervention_count = Column(Integer, default=0)
    intervention_success_rate = Column(Float, default=0.0)  # 0-100%
    avg_mindless_score = Column(Float, default=0.0)
    time_reclaimed_minutes = Column(Float, default=0.0)
    
    computed_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    __table_args__ = (
        Index('idx_daily_stats_user_date', 'user_id', 'date'),
    )

class SessionMetrics(Base):
    """Track individual session metrics for detailed analysis"""
    __tablename__ = "session_metrics"
    
    id = Column(Integer, primary_key=True, autoincrement=True)
    user_id = Column(String, ForeignKey("users.id"), nullable=False, index=True)
    session_start = Column(DateTime, nullable=False, index=True)
    session_end = Column(DateTime, nullable=False)
    platform = Column(String, nullable=False)
    
    # Session statistics
    total_duration_seconds = Column(Integer, default=0)
    scroll_count = Column(Integer, default=0)
    avg_scroll_velocity = Column(Float, default=0.0)
    posts_viewed = Column(Integer, default=0)
    posts_bypassed = Column(Integer, default=0)
    avg_dwell_time = Column(Float, default=0.0)
    click_count = Column(Integer, default=0)
    interventions_received = Column(Integer, default=0)
    user_followed_intervention = Column(Boolean, default=False)
    
    # Mindfulness score for session
    mindless_score = Column(Float, default=0.0)
    focus_score = Column(Float, default=0.0)  # Inverse of mindless
    
    __table_args__ = (
        Index('idx_session_user_date', 'user_id', 'session_start'),
    )
